
# Override ALL services to use both default and scripts_default networks
services:
  redis:
    image: quay.io/insights-onprem/redis-ephemeral:6

  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z

  create-parquet-bucket:
    image: quay.io/minio/mc:latest
  # Add any other services you have...
